<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('products')->delete();
        
        \DB::table('products')->insert(array (
            0 => 
            array (
                'id' => 1,
                'sku' => '0006CZ001',
                'name' => 'Estante De Aço Multi-uso 25cm 5 Prateleira Cinza',
                'slug' => 'estante-de-aco-multi-uso-25cm-5-prateleira-cinza',
                'color' => 'Cinza',
                'description' => 'Estante de Aço 25cm com 5 Prateleiras Reguláveis cor Cinza
Suporta até 25 kg distribuídos por prateleira,',
                'base_currency' => 'R$',
                'price' => 9900,
                'price_max' => 12000,
                'stock' => 22,
                'image' => 'https://www.supreme.ind.br/imagem/estantes/estante-05-bandejas/estante-30-5-prateleiras-cinza.png',
                'order' => 5,
                'active' => 1,
                'group_id' => 1,
                'created_at' => '2021-04-11 18:54:54',
                'updated_at' => '2021-04-18 20:57:23',
            ),
            1 => 
            array (
                'id' => 2,
                'sku' => '0006AZ001',
                'name' => 'Estante De Aço Multi-uso 25cm 5 Prateleira azul',
                'slug' => 'estante-de-aco-multi-uso-25cm-5-prateleira-azul',
                'color' => 'azul',
                'description' => 'Estante de Aço 25cm com 5 Prateleiras Reguláveis cor Cinza
Suporta até 25 kg distribuídos por prateleira,',
                'base_currency' => 'R$',
                'price' => 12000,
                'price_max' => 12000,
                'stock' => 33,
                'image' => 'http://supreme.ind.br/imagem/estantes/estante-06-bandejas/estante-30cm-6-bandejas-azul-bic.jpg',
                'order' => 1,
                'active' => 1,
                'group_id' => 1,
                'created_at' => '2021-04-18 15:11:19',
                'updated_at' => '2021-04-18 21:11:19',
            ),
            2 => 
            array (
                'id' => 3,
                'sku' => '0006AM001',
                'name' => 'Estante De Aço Multi-uso 25cm 5 Prateleira amarela',
                'slug' => 'estante-de-aco-multi-uso-25cm-5-prateleira-amarela',
                'color' => 'amarela',
                'description' => 'Estante de Aço 25cm com 5 Prateleiras Reguláveis cor Amarela
Suporta até 25 kg distribuídos por prateleira,',
                'base_currency' => 'R$',
                'price' => 12000,
                'price_max' => 12000,
                'stock' => 33,
                'image' => 'http://supreme.ind.br/imagem/estantes/estante-03-bandejas/estante-25cm-3-bandejas-cinza.png',
                'order' => 1,
                'active' => 0,
                'group_id' => 1,
                'created_at' => '2021-04-18 15:11:19',
                'updated_at' => '2021-04-18 21:12:16',
            ),
            3 => 
            array (
                'id' => 4,
                'sku' => '0006RO001',
                'name' => 'Estante De Aço Multi-uso 25cm 5 Prateleira Rosa',
                'slug' => 'estante-de-aco-multi-uso-25cm-5-prateleira-rosa',
                'color' => 'Rosa',
                'description' => 'Estante de Aço 25cm com 5 Prateleiras Reguláveis cor Cinza
Suporta até 25 kg distribuídos por prateleira,',
                'base_currency' => 'R$',
                'price' => 12000,
                'price_max' => 12000,
                'stock' => 33,
                'image' => 'https://www.supreme.ind.br/imagem/estantes/estante-05-bandejas/estante-30-5-prateleiras-rosa.png',
                'order' => 1,
                'active' => 1,
                'group_id' => 1,
                'created_at' => '2021-04-18 15:11:19',
                'updated_at' => '2021-04-18 20:57:40',
            ),
            4 => 
            array (
                'id' => 5,
                'sku' => '0006VE001',
                'name' => 'Estante De Aço Multi-uso 25cm 5 Prateleira Vermelha',
                'slug' => 'estante-de-aco-multi-uso-25cm-5-prateleira-vermelha',
                'color' => 'Vermelha',
                'description' => 'Estante de Aço 25cm com 5 Prateleiras Reguláveis cor Cinza
Suporta até 25 kg distribuídos por prateleira,',
                'base_currency' => 'R$',
                'price' => 12000,
                'price_max' => 12000,
                'stock' => 33,
                'image' => 'http://supreme.ind.br/imagem/estantes/estante-06-bandejas/estante-30cm-6-bandejas-vermelho.jpg',
                'order' => 1,
                'active' => 1,
                'group_id' => 1,
                'created_at' => '2021-04-18 15:11:19',
                'updated_at' => '2021-04-18 21:08:09',
            ),
            5 => 
            array (
                'id' => 6,
                'sku' => '0006VD001',
                'name' => 'Estante De Aço Multi-uso 25cm 5 Prateleira Verde',
                'slug' => 'estante-de-aco-multi-uso-25cm-5-prateleira-verde',
                'color' => 'Verde',
                'description' => 'Estante de Aço 25cm com 5 Prateleiras Reguláveis cor Verde
Suporta até 25 kg distribuídos por prateleira,',
                'base_currency' => 'R$',
                'price' => 12000,
                'price_max' => 12000,
                'stock' => 33,
                'image' => 'http://supreme.ind.br/imagem/estantes/estante-06-bandejas/estante-30cm-6-bandejas-verde.jpg',
                'order' => 1,
                'active' => 1,
                'group_id' => 1,
                'created_at' => '2021-04-18 15:11:19',
                'updated_at' => '2021-04-18 21:10:03',
            ),
            6 => 
            array (
                'id' => 7,
                'sku' => '0002AZ001',
                'name' => 'Estante De Aço Multi-uso 30cm 6 Prateleira azul',
                'slug' => 'estante-de-aco-multi-uso-30cm-6-prateleira-azul',
                'color' => 'azul',
                'description' => 'Estante de Aço 30cm com 6 Prateleiras Reguláveis cor Cinza
Suporta até 25 kg distribuídos por prateleira,',
                'base_currency' => 'R$',
                'price' => 13000,
                'price_max' => 13000,
                'stock' => 33,
                'image' => 'http://supreme.ind.br/imagem/estantes/estante-06-bandejas/estante-30cm-6-bandejas-azul-bic.jpg',
                'order' => 1,
                'active' => 1,
                'group_id' => 2,
                'created_at' => '2021-04-18 15:11:19',
                'updated_at' => '2021-04-18 21:11:27',
            ),
            7 => 
            array (
                'id' => 8,
                'sku' => '0002CZ001',
                'name' => 'Estante De Aço Multi-uso 30cm 6 Prateleira Cinza',
                'slug' => 'estante-de-aco-multi-uso-30cm-6-prateleira-cinza',
                'color' => 'Cinza',
                'description' => 'Estante de Aço 30cm com 6 Prateleiras Reguláveis cor Cinza
Suporta até 25 kg distribuídos por prateleira,',
                'base_currency' => 'R$',
                'price' => 13000,
                'price_max' => 13000,
                'stock' => 33,
                'image' => 'http://supreme.ind.br/imagem/estantes/estante-03-bandejas/estante-25cm-3-bandejas-cinza.png',
                'order' => 1,
                'active' => 1,
                'group_id' => 2,
                'created_at' => '2021-04-18 15:11:19',
                'updated_at' => '2021-04-18 21:12:27',
            ),
            8 => 
            array (
                'id' => 9,
                'sku' => '0006UV001',
                'name' => 'Estante De Aço Multi-uso 25cm 5 Prateleira Uva',
                'slug' => 'estante-de-aco-multi-uso-25cm-5-prateleira-uva',
                'color' => 'Uva',
                'description' => 'Estante de Aço 25cm com 5 Prateleiras Reguláveis cor Cinza
Suporta até 25 kg distribuídos por prateleira,',
                'base_currency' => 'R$',
                'price' => 9900,
                'price_max' => 12000,
                'stock' => 22,
                'image' => 'https://www.supreme.ind.br/imagem/estantes/estante-05-bandejas/estante-30-5-prateleiras-cinza.png',
                'order' => 1,
                'active' => 1,
                'group_id' => 1,
                'created_at' => '2021-04-18 20:42:36',
                'updated_at' => '2021-04-18 20:58:27',
            ),
            9 => 
            array (
                'id' => 10,
                'sku' => '0006PE001',
                'name' => 'Estante De Aço Multi-uso 25cm 5 Prateleira Preta',
                'slug' => 'estante-de-aco-multi-uso-25cm-5-prateleira-preta',
                'color' => 'Preta',
                'description' => 'Estante de Aço 25cm com 5 Prateleiras Reguláveis cor Cinza
Suporta até 25 kg distribuídos por prateleira,',
                'base_currency' => 'R$',
                'price' => 12000,
                'price_max' => 12000,
                'stock' => 33,
                'image' => 'https://www.supreme.ind.br/imagem/estantes/estante-05-bandejas/estante-30-5-prateleiras-cinza.png',
                'order' => 1,
                'active' => 1,
                'group_id' => 1,
                'created_at' => '2021-04-18 20:42:36',
                'updated_at' => '2021-04-18 20:58:39',
            ),
            10 => 
            array (
                'id' => 11,
                'sku' => '0006BG001',
                'name' => 'Estante De Aço Multi-uso 25cm 5 Prateleira Bege',
                'slug' => 'estante-de-aco-multi-uso-25cm-5-prateleira-bege',
                'color' => 'Bege',
                'description' => 'Estante de Aço 25cm com 5 Prateleiras Reguláveis cor Amarela
Suporta até 25 kg distribuídos por prateleira,',
                'base_currency' => 'R$',
                'price' => 12000,
                'price_max' => 12000,
                'stock' => 33,
                'image' => 'http://supreme.ind.br/imagem/estantes/estante-03-bandejas/estante-25cm-3-bandejas-cinza.png',
                'order' => 1,
                'active' => 0,
                'group_id' => 1,
                'created_at' => '2021-04-18 20:42:36',
                'updated_at' => '2021-04-18 21:13:04',
            ),
            11 => 
            array (
                'id' => 12,
                'sku' => '0006VI001',
                'name' => 'Estante De Aço Multi-uso 25cm 5 Prateleira Vinho',
                'slug' => 'estante-de-aco-multi-uso-25cm-5-prateleira-vinho',
                'color' => 'Vinho',
                'description' => 'Estante de Aço 25cm com 5 Prateleiras Reguláveis cor Cinza
Suporta até 25 kg distribuídos por prateleira,',
                'base_currency' => 'R$',
                'price' => 12000,
                'price_max' => 12000,
                'stock' => 33,
                'image' => 'https://www.supreme.ind.br/imagem/estantes/estante-05-bandejas/estante-30-5-prateleiras-rosa.png',
                'order' => 1,
                'active' => 1,
                'group_id' => 1,
                'created_at' => '2021-04-18 20:42:36',
                'updated_at' => '2021-04-18 20:58:55',
            ),
            12 => 
            array (
                'id' => 13,
                'sku' => '0006BR001',
                'name' => 'Estante De Aço Multi-uso 25cm 5 Prateleira Branca',
                'slug' => 'estante-de-aco-multi-uso-25cm-5-prateleira-branca',
                'color' => 'Branca',
                'description' => 'Estante de Aço 25cm com 5 Prateleiras Reguláveis cor Cinza
Suporta até 25 kg distribuídos por prateleira,',
                'base_currency' => 'R$',
                'price' => 12000,
                'price_max' => 12000,
                'stock' => 33,
                'image' => 'http://supreme.ind.br/imagem/estantes/estante-03-bandejas/estante-25cm-3-bandejas-cinza.png',
                'order' => 1,
                'active' => 1,
                'group_id' => 1,
                'created_at' => '2021-04-18 20:42:37',
                'updated_at' => '2021-04-18 21:12:37',
            ),
            13 => 
            array (
                'id' => 14,
                'sku' => '0006LI001',
                'name' => 'Estante De Aço Multi-uso 25cm 5 Prateleira Lilas',
                'slug' => 'estante-de-aco-multi-uso-25cm-5-prateleira-lilas',
                'color' => 'Lilas',
                'description' => 'Estante de Aço 25cm com 5 Prateleiras Reguláveis cor Verde
Suporta até 25 kg distribuídos por prateleira,',
                'base_currency' => 'R$',
                'price' => 12000,
                'price_max' => 12000,
                'stock' => 33,
                'image' => 'https://www.supreme.ind.br/imagem/estantes/estante-05-bandejas/estante-30-5-prateleiras-Verde.png',
                'order' => 1,
                'active' => 1,
                'group_id' => 1,
                'created_at' => '2021-04-18 20:42:37',
                'updated_at' => '2021-04-18 20:59:17',
            ),
            14 => 
            array (
                'id' => 15,
                'sku' => '0006LA001',
                'name' => 'Estante De Aço Multi-uso 25cm 5 Prateleira Laranja',
                'slug' => 'estante-de-aco-multi-uso-25cm-5-prateleira-laranja',
                'color' => 'Laranja',
                'description' => 'Estante de Aço 25cm com 5 Prateleiras Reguláveis cor Verde
Suporta até 25 kg distribuídos por prateleira,',
                'base_currency' => 'R$',
                'price' => 12000,
                'price_max' => 12000,
                'stock' => 33,
                'image' => 'http://supreme.ind.br/imagem/estantes/estante-03-bandejas/estante-25cm-3-bandejas-cinza.png',
                'order' => 1,
                'active' => 1,
                'group_id' => 1,
                'created_at' => '2021-04-18 20:42:37',
                'updated_at' => '2021-04-18 21:12:46',
            ),
            15 => 
            array (
                'id' => 16,
                'sku' => '0002UV001',
                'name' => 'Estante De Aço Multi-uso 30cm 6 Prateleira Uva',
                'slug' => 'estante-de-aco-multi-uso-30cm-6-prateleira-uva',
                'color' => 'Uva',
                'description' => 'Estante de Aço 30cm com 6 Prateleiras Reguláveis cor Cinza
Suporta até 25 kg distribuídos por prateleira,',
                'base_currency' => 'R$',
                'price' => 13000,
                'price_max' => 13000,
                'stock' => 33,
                'image' => 'http://supreme.ind.br/imagem/estantes/estante-06-bandejas/estante-30cm-6-bandejas-vermelho.jpg',
                'order' => 1,
                'active' => 1,
                'group_id' => 2,
                'created_at' => '2021-04-18 20:42:37',
                'updated_at' => '2021-04-18 21:13:23',
            ),
            16 => 
            array (
                'id' => 17,
                'sku' => '0002PE001',
                'name' => 'Estante De Aço Multi-uso 30cm 6 Prateleira preta',
                'slug' => 'estante-de-aco-multi-uso-30cm-6-prateleira-preta',
                'color' => 'Preto',
                'description' => 'Estante de Aço 30cm com 6 Prateleiras Reguláveis cor Cinza
Suporta até 25 kg distribuídos por prateleira,',
                'base_currency' => 'R$',
                'price' => 13000,
                'price_max' => 13000,
                'stock' => 33,
                'image' => 'http://supreme.ind.br/imagem/estantes/estante-06-bandejas/estante-30cm-6-bandejas-vermelho.jpg',
                'order' => 1,
                'active' => 1,
                'group_id' => 2,
                'created_at' => '2021-04-18 20:42:37',
                'updated_at' => '2021-04-18 21:09:13',
            ),
            17 => 
            array (
                'id' => 18,
                'sku' => '0002BE001',
                'name' => 'Estante De Aço Multi-uso 30cm 6 Prateleira bege',
                'slug' => 'estante-de-aco-multi-uso-30cm-6-prateleira-bege',
                'color' => 'Bege',
                'description' => 'Estante de Aço 30cm com 6 Prateleiras Reguláveis cor Cinza
Suporta até 25 kg distribuídos por prateleira,',
                'base_currency' => 'R$',
                'price' => 13000,
                'price_max' => 13000,
                'stock' => 33,
                'image' => 'https://www.supreme.ind.br/imagem/estantes/estante-05-bandejas/estante-30-6-prateleiras-azul.png',
                'order' => 1,
                'active' => 1,
                'group_id' => 2,
                'created_at' => '2021-04-18 20:42:37',
                'updated_at' => '2021-04-18 20:49:33',
            ),
            18 => 
            array (
                'id' => 19,
                'sku' => '0002AB001',
                'name' => 'Estante De Aço Multi-uso 30cm 6 Prateleira azul bic',
                'slug' => 'estante-de-aco-multi-uso-30cm-6-prateleira-azul-bic',
                'color' => 'azul bic',
                'description' => 'Estante de Aço 30cm com 6 Prateleiras Reguláveis cor Cinza
Suporta até 25 kg distribuídos por prateleira,',
                'base_currency' => 'R$',
                'price' => 13000,
                'price_max' => 13000,
                'stock' => 33,
                'image' => 'http://supreme.ind.br/imagem/estantes/estante-06-bandejas/estante-30cm-6-bandejas-azul-bic.jpg',
                'order' => 1,
                'active' => 1,
                'group_id' => 2,
                'created_at' => '2021-04-18 20:42:37',
                'updated_at' => '2021-04-18 21:11:35',
            ),
            19 => 
            array (
                'id' => 20,
                'sku' => '0002VE001',
                'name' => 'Estante De Aço Multi-uso 30cm 6 Prateleira vermelha',
                'slug' => 'estante-de-aco-multi-uso-30cm-6-prateleira-vermelha',
                'color' => 'vermelho',
                'description' => 'Estante de Aço 30cm com 6 Prateleiras Reguláveis cor Cinza
Suporta até 25 kg distribuídos por prateleira,',
                'base_currency' => 'R$',
                'price' => 13000,
                'price_max' => 13000,
                'stock' => 33,
                'image' => 'http://supreme.ind.br/imagem/estantes/estante-06-bandejas/estante-30cm-6-bandejas-vermelho.jpg',
                'order' => 1,
                'active' => 1,
                'group_id' => 2,
                'created_at' => '2021-04-18 20:42:37',
                'updated_at' => '2021-04-18 21:08:31',
            ),
            20 => 
            array (
                'id' => 21,
                'sku' => '0002RO001',
                'name' => 'Estante De Aço Multi-uso 30cm 6 Prateleira rosa',
                'slug' => 'estante-de-aco-multi-uso-30cm-6-prateleira-rosa',
                'color' => 'Rosa',
                'description' => 'Estante de Aço 30cm com 6 Prateleiras Reguláveis cor Cinza
Suporta até 25 kg distribuídos por prateleira,',
                'base_currency' => 'R$',
                'price' => 13000,
                'price_max' => 13000,
                'stock' => 33,
                'image' => 'http://supreme.ind.br/imagem/estantes/estante-06-bandejas/estante-30cm-6-bandejas-rosa.jpg',
                'order' => 1,
                'active' => 0,
                'group_id' => 2,
                'created_at' => '2021-04-18 20:42:37',
                'updated_at' => '2021-04-18 21:10:42',
            ),
            21 => 
            array (
                'id' => 22,
                'sku' => '0002VD001',
                'name' => 'Estante De Aço Multi-uso 30cm 6 Prateleira verde',
                'slug' => 'estante-de-aco-multi-uso-30cm-6-prateleira-verde',
                'color' => 'Verde',
                'description' => 'Estante de Aço 30cm com 6 Prateleiras Reguláveis cor Cinza
Suporta até 25 kg distribuídos por prateleira,',
                'base_currency' => 'R$',
                'price' => 13000,
                'price_max' => 13000,
                'stock' => 33,
                'image' => 'http://supreme.ind.br/imagem/estantes/estante-06-bandejas/estante-30cm-6-bandejas-verde.jpg',
                'order' => 1,
                'active' => 1,
                'group_id' => 2,
                'created_at' => '2021-04-18 20:42:37',
                'updated_at' => '2021-04-18 21:10:13',
            ),
            22 => 
            array (
                'id' => 23,
                'sku' => '0002VI001',
                'name' => 'Estante De Aço Multi-uso 30cm 6 Prateleira vinho',
                'slug' => 'estante-de-aco-multi-uso-30cm-6-prateleira-vinho',
                'color' => 'Vinho',
                'description' => 'Estante de Aço 30cm com 6 Prateleiras Reguláveis cor Cinza
Suporta até 25 kg distribuídos por prateleira,',
                'base_currency' => 'R$',
                'price' => 13000,
                'price_max' => 13000,
                'stock' => 33,
                'image' => 'https://www.supreme.ind.br/imagem/estantes/estante-05-bandejas/estante-30-6-prateleiras-cinza.png',
                'order' => 1,
                'active' => 1,
                'group_id' => 2,
                'created_at' => '2021-04-18 20:42:37',
                'updated_at' => '2021-04-18 20:49:33',
            ),
            23 => 
            array (
                'id' => 24,
                'sku' => '0002BR001',
                'name' => 'Estante De Aço Multi-uso 30cm 6 Prateleira branca',
                'slug' => 'estante-de-aco-multi-uso-30cm-6-prateleira-branca',
                'color' => 'branco',
                'description' => 'Estante de Aço 30cm com 6 Prateleiras Reguláveis cor Cinza
Suporta até 25 kg distribuídos por prateleira,',
                'base_currency' => 'R$',
                'price' => 13000,
                'price_max' => 13000,
                'stock' => 33,
                'image' => 'https://www.supreme.ind.br/imagem/estantes/estante-05-bandejas/estante-30-5-prateleiras-amarela.png',
                'order' => 1,
                'active' => 1,
                'group_id' => 2,
                'created_at' => '2021-04-18 20:42:37',
                'updated_at' => '2021-04-18 21:13:54',
            ),
            24 => 
            array (
                'id' => 25,
                'sku' => '0002AM001',
                'name' => 'Estante De Aço Multi-uso 30cm 6 Prateleira amarela',
                'slug' => 'estante-de-aco-multi-uso-30cm-6-prateleira-amarela',
                'color' => 'amarelo',
                'description' => 'Estante de Aço 30cm com 6 Prateleiras Reguláveis cor Cinza
Suporta até 25 kg distribuídos por prateleira,',
                'base_currency' => 'R$',
                'price' => 13000,
                'price_max' => 13000,
                'stock' => 33,
                'image' => 'https://www.supreme.ind.br/imagem/estantes/estante-05-bandejas/estante-30-5-prateleiras-amarela.png',
                'order' => 1,
                'active' => 1,
                'group_id' => 2,
                'created_at' => '2021-04-18 20:42:37',
                'updated_at' => '2021-04-18 21:13:33',
            ),
            25 => 
            array (
                'id' => 26,
                'sku' => '0002LI001',
                'name' => 'Estante De Aço Multi-uso 30cm 6 Prateleira lilas',
                'slug' => 'estante-de-aco-multi-uso-30cm-6-prateleira-lilas',
                'color' => 'lilas',
                'description' => 'Estante de Aço 30cm com 6 Prateleiras Reguláveis cor Cinza
Suporta até 25 kg distribuídos por prateleira,',
                'base_currency' => 'R$',
                'price' => 13000,
                'price_max' => 13000,
                'stock' => 33,
                'image' => 'https://www.supreme.ind.br/imagem/estantes/estante-05-bandejas/estante-30-5-prateleiras-rosa.png',
                'order' => 1,
                'active' => 1,
                'group_id' => 2,
                'created_at' => '2021-04-18 20:42:37',
                'updated_at' => '2021-04-18 21:13:45',
            ),
            26 => 
            array (
                'id' => 27,
                'sku' => '0002LA001',
                'name' => 'Estante De Aço Multi-uso 30cm 6 Prateleira laranja',
                'slug' => 'estante-de-aco-multi-uso-30cm-6-prateleira-laranja',
                'color' => 'laranja',
                'description' => 'Estante de Aço 30cm com 6 Prateleiras Reguláveis cor Cinza
Suporta até 25 kg distribuídos por prateleira,',
                'base_currency' => 'R$',
                'price' => 13000,
                'price_max' => 13000,
                'stock' => 33,
                'image' => 'https://www.supreme.ind.br/imagem/estantes/estante-05-bandejas/estante-30-6-prateleiras-azul.png',
                'order' => 1,
                'active' => 1,
                'group_id' => 2,
                'created_at' => '2021-04-18 20:42:37',
                'updated_at' => '2021-04-18 20:49:33',
            ),
            27 => 
            array (
                'id' => 28,
                'sku' => '0005PE001',
                'name' => 'Estante De Aço Multi-uso 40cm 6 Prateleira preta',
                'slug' => 'estante-de-aco-multi-uso-40cm-6-prateleira-preta',
                'color' => 'preto',
                'description' => 'Estante de Aço 40cm com 6 Prateleiras Reguláveis cor Cinza
Suporta até 25 kg distribuídos por prateleira,',
                'base_currency' => 'R$',
                'price' => 13000,
                'price_max' => 13000,
                'stock' => 33,
                'image' => 'http://supreme.ind.br/imagem/estantes/estante-EP3/estante-de-aco-30cm-3-bandejas-decorativa-colorida-preta.jpg',
                'order' => 1,
                'active' => 1,
                'group_id' => 3,
                'created_at' => '2021-04-18 20:52:41',
                'updated_at' => '2021-04-18 21:09:28',
            ),
            28 => 
            array (
                'id' => 29,
                'sku' => '0005BG001',
                'name' => 'Estante De Aço Multi-uso 40cm 6 Prateleira bege',
                'slug' => 'estante-de-aco-multi-uso-40cm-6-prateleira-bege',
                'color' => 'bege',
                'description' => 'Estante de Aço 30cm com 6 Prateleiras Reguláveis cor Cinza
Suporta até 25 kg distribuídos por prateleira,',
                'base_currency' => 'R$',
                'price' => 13000,
                'price_max' => 13000,
                'stock' => 33,
                'image' => 'https://www.supreme.ind.br/imagem/estantes/estante-05-bandejas/estante-30-6-prateleiras-cinza.png',
                'order' => 1,
                'active' => 1,
                'group_id' => 3,
                'created_at' => '2021-04-18 20:52:41',
                'updated_at' => '2021-04-18 20:52:41',
            ),
            29 => 
            array (
                'id' => 30,
                'sku' => '0005VE001',
                'name' => 'Estante De Aço Multi-uso 40cm 6 Prateleira vermelha',
                'slug' => 'estante-de-aco-multi-uso-40cm-6-prateleira-vermelha',
                'color' => 'vermelho',
                'description' => 'Estante de Aço 30cm com 6 Prateleiras Reguláveis cor Cinza
Suporta até 25 kg distribuídos por prateleira,',
                'base_currency' => 'R$',
                'price' => 13000,
                'price_max' => 13000,
                'stock' => 33,
                'image' => 'http://supreme.ind.br/imagem/estantes/estante-06-bandejas/estante-30cm-6-bandejas-vermelho.jpg',
                'order' => 1,
                'active' => 1,
                'group_id' => 3,
                'created_at' => '2021-04-18 20:52:41',
                'updated_at' => '2021-04-18 21:08:42',
            ),
            30 => 
            array (
                'id' => 31,
                'sku' => '0005RO001',
                'name' => 'Estante De Aço Multi-uso 40cm 6 Prateleira rosa',
                'slug' => 'estante-de-aco-multi-uso-40cm-6-prateleira-rosa',
                'color' => 'rosa',
                'description' => 'Estante de Aço 30cm com 6 Prateleiras Reguláveis cor Cinza
Suporta até 25 kg distribuídos por prateleira,',
                'base_currency' => 'R$',
                'price' => 13000,
                'price_max' => 13000,
                'stock' => 33,
                'image' => 'http://supreme.ind.br/imagem/estantes/estante-06-bandejas/estante-30cm-6-bandejas-rosa.jpg',
                'order' => 1,
                'active' => 1,
                'group_id' => 3,
                'created_at' => '2021-04-18 20:52:41',
                'updated_at' => '2021-04-18 21:10:52',
            ),
            31 => 
            array (
                'id' => 32,
                'sku' => '0005BR001',
                'name' => 'Estante De Aço Multi-uso 40cm 6 Prateleira branca',
                'slug' => 'estante-de-aco-multi-uso-40cm-6-prateleira-branca',
                'color' => 'branco',
                'description' => 'Estante de Aço 30cm com 6 Prateleiras Reguláveis cor Cinza
Suporta até 25 kg distribuídos por prateleira,',
                'base_currency' => 'R$',
                'price' => 13000,
                'price_max' => 13000,
                'stock' => 33,
                'image' => 'https://www.supreme.ind.br/imagem/estantes/estante-05-bandejas/estante-30-6-prateleiras-cinza.png',
                'order' => 1,
                'active' => 1,
                'group_id' => 3,
                'created_at' => '2021-04-18 20:56:02',
                'updated_at' => '2021-04-18 20:56:02',
            ),
            32 => 
            array (
                'id' => 33,
                'sku' => '0005AM001',
                'name' => 'Estante De Aço Multi-uso 40cm 6 Prateleira amarela',
                'slug' => 'estante-de-aco-multi-uso-40cm-6-prateleira-amarela',
                'color' => 'amarelo',
                'description' => 'Estante de Aço 30cm com 6 Prateleiras Reguláveis cor Cinza
Suporta até 25 kg distribuídos por prateleira,',
                'base_currency' => 'R$',
                'price' => 13000,
                'price_max' => 13000,
                'stock' => 33,
                'image' => 'https://www.supreme.ind.br/imagem/estantes/estante-05-bandejas/estante-30-5-prateleiras-amarelo.png',
                'order' => 1,
                'active' => 1,
                'group_id' => 3,
                'created_at' => '2021-04-18 20:56:02',
                'updated_at' => '2021-04-18 21:14:10',
            ),
            33 => 
            array (
                'id' => 34,
                'sku' => '0005LI001',
                'name' => 'Estante De Aço Multi-uso 40cm 6 Prateleira lilas',
                'slug' => 'estante-de-aco-multi-uso-40cm-6-prateleira-lilas',
                'color' => 'lilas',
                'description' => 'Estante de Aço 30cm com 6 Prateleiras Reguláveis cor Cinza
Suporta até 25 kg distribuídos por prateleira,',
                'base_currency' => 'R$',
                'price' => 13000,
                'price_max' => 13000,
                'stock' => 33,
                'image' => 'https://www.supreme.ind.br/imagem/estantes/estante-05-bandejas/estante-30-5-prateleiras-lilas.png',
                'order' => 1,
                'active' => 1,
                'group_id' => 3,
                'created_at' => '2021-04-18 20:56:02',
                'updated_at' => '2021-04-18 21:14:20',
            ),
            34 => 
            array (
                'id' => 35,
                'sku' => '0005LA001',
                'name' => 'Estante De Aço Multi-uso 40cm 6 Prateleira laranja',
                'slug' => 'estante-de-aco-multi-uso-40cm-6-prateleira-laranja',
                'color' => 'laranja',
                'description' => 'Estante de Aço 30cm com 6 Prateleiras Reguláveis cor Cinza
Suporta até 25 kg distribuídos por prateleira,',
                'base_currency' => 'R$',
                'price' => 13000,
                'price_max' => 13000,
                'stock' => 33,
                'image' => 'https://www.supreme.ind.br/imagem/estantes/estante-05-bandejas/estante-30-5-prateleiras-rosa.png',
                'order' => 1,
                'active' => 1,
                'group_id' => 3,
                'created_at' => '2021-04-18 20:56:02',
                'updated_at' => '2021-04-18 21:14:40',
            ),
            35 => 
            array (
                'id' => 36,
                'sku' => '0005AZ001',
                'name' => 'Estante De Aço Multi-uso 40cm 6 Prateleira azul',
                'slug' => 'estante-de-aco-multi-uso-40cm-6-prateleira-azul',
                'color' => 'azul',
                'description' => 'Estante de Aço 30cm com 6 Prateleiras Reguláveis cor Cinza
Suporta até 25 kg distribuídos por prateleira,',
                'base_currency' => 'R$',
                'price' => 13000,
                'price_max' => 13000,
                'stock' => 33,
                'image' => 'http://supreme.ind.br/imagem/estantes/estante-06-bandejas/estante-30cm-6-bandejas-azul-bic.jpg',
                'order' => 1,
                'active' => 1,
                'group_id' => 3,
                'created_at' => '2021-04-18 20:56:02',
                'updated_at' => '2021-04-18 21:11:44',
            ),
            36 => 
            array (
                'id' => 37,
                'sku' => '0258VE002',
                'name' => 'Roupeiro De Aço 6 Portas Grp2/6 Corpo Cinza Portas Vermelhas',
                'slug' => 'roupeiro-de-aco-6-portas-grp26-corpo-cinza-portas-vermelhas',
                'color' => 'Vermelha',
                'description' => NULL,
                'base_currency' => NULL,
                'price' => 65200,
                'price_max' => 75400,
                'stock' => 54,
                'image' => 'http://supreme.ind.br/imagem/roupeiros/grp-4/corpo-cinza/roupeiro-grp4-corpo-cinza-portas-vinho.jpg',
                'order' => 3,
                'active' => 1,
                'group_id' => 4,
                'created_at' => '2021-04-18 22:16:28',
                'updated_at' => '2021-04-18 22:17:08',
            ),
            37 => 
            array (
                'id' => 38,
                'sku' => '0258VI001',
                'name' => 'Roupeiro De Aço 16 Portas Grp8/16 Academia Vinho',
                'slug' => 'roupeiro-de-aco-16-portas-grp816-academia-vinho',
                'color' => 'Vinho',
                'description' => NULL,
                'base_currency' => NULL,
                'price' => 85266,
                'price_max' => 95204,
                'stock' => 87,
                'image' => 'http://supreme.ind.br/imagem/roupeiros/grp-8/corpo-cinza/roupeiro-grp8-corpo-cinza-portas-azul-texturizado.jpg',
                'order' => 5,
                'active' => 1,
                'group_id' => 4,
                'created_at' => '2021-04-18 22:19:35',
                'updated_at' => '2021-04-18 22:19:35',
            ),
            38 => 
            array (
                'id' => 39,
                'sku' => '0015VI001',
                'name' => 'Armario De Aço A90 Com 2 Portas Supreme Vinho',
                'slug' => 'armario-de-aco-a90-com-2-portas-supreme-vinho',
                'color' => 'Vinho',
                'description' => NULL,
                'base_currency' => NULL,
                'price' => 78955,
                'price_max' => 87955,
                'stock' => 14,
                'image' => 'http://supreme.ind.br/imagem/armarios/a90/corpo-branco/armario-a90-corpo-branco-portas-vinho.jpg',
                'order' => 3,
                'active' => 1,
                'group_id' => 5,
                'created_at' => '2021-04-18 22:23:51',
                'updated_at' => '2021-04-18 22:23:51',
            ),
            39 => 
            array (
                'id' => 40,
                'sku' => '0015AM001',
                'name' => 'Armario De Aço A90 Com 2 Portas Supreme Amarelo',
                'slug' => 'armario-de-aco-a90-com-2-portas-supreme-amarelo',
                'color' => 'amarela',
                'description' => NULL,
                'base_currency' => NULL,
                'price' => 78900,
                'price_max' => 87955,
                'stock' => 65,
                'image' => 'http://supreme.ind.br/imagem/armarios/a15/corpo-cinza/armario-a15-corpo-cinza-porta-amarela.png',
                'order' => 5,
                'active' => 1,
                'group_id' => 5,
                'created_at' => '2021-04-18 22:25:13',
                'updated_at' => '2021-04-18 22:25:13',
            ),
        ));
        
        
    }
}